### PR TITLE
bug fixed

### LINKED ISSUE #142: Bug: Update calendar dosn't work

### PR DESCRIPTION
**Pull request by splotchysnow**

### CODE REVIEW

File: source/assets/scripts/middle-ground.js [hunk 1]
```diff
@@ -20,14 +20,23 @@ function getCalendarFromStorage() {
...
   let oldCalendarStorage = getCalendarFromStorage();
   oldCalendarStorage.push(json_file);
   localStorage.setItem("calendars", JSON.stringify(oldCalendarStorage));
 }
 
+/**
+ * @author Guan Li
+ * @summary takes in a parameter calendar and save it to storage
+ */
+ function saveOnlyNewCalendarToStorage(json_file) {
```
Comment (stevenkhaw) [inline source/assets/scripts/middle-ground.js]: run prettier.js on the code to fix linting issues

**Review by stevenkhaw — CHANGES_REQUESTED** [review]
